### ISSUE TITLE
Базовый искуственный интеллект: Передвижение

### ISSUE THREAD

**Issue by Sha-a-ake** [Sha-a-ake/There-s-no-space-for-peace#17]
Необходимо написать следующие паттерны поведения для врагов:

Передвижение к заданной цели
Передвижение от заданной цели

**Comment by Evg-Mazay** [comment]
от заданной цели в конкретное место? Или просто Find_Path('Run!') в рандомном направлении

**Comment by Sha-a-ake** [comment]
Функция принимающая в аргументы координаты цели.
def MoveTo(x,y)
Дабы потом можно было вызывать как MoveTo(HumieX,HumieY)
