### ISSUE TITLE
Базовый искусственный интеллект: условия

### ISSUE THREAD

**Issue by Sha-a-ake** [Sha-a-ake/There-s-no-space-for-peace#18]
Необходимо сделать несколько булевых переменных внутри класса droid
которые будут отслеживать:
Не слишком ли далеко игрок 
Не слишком ли близко игрок
Находится ли игрок на одной с объектом линии
Находится ли игрок на одной из соседних с объектом клетках

Привязать минимальное/максимальное расстояние для двух первых условий к константам.
Можно написать отдельную функцию Evaluate которая будет пересчитывать состояние переменных

**Comment by Evg-Mazay** [comment]
Константы записывать в Const или в класс?
На одной с объектом линии считается, если есть препятствия?
Также 'насколько далеко' - это путь с учётом препятствий, или расстояние по прямой линии?
И должен ли враг видеть сквозь стены?

**Comment by Sha-a-ake** [comment]
В класс, дабы эту константу можно было регулировать изнутри индивидуально для каждого моба.
Можно считать стены, не других врагов
В идеале считать по теореме Пифагора
Нет

**Comment by Evg-Mazay** [comment]
Доделал переменную Near (последний пункт)
