### ISSUE TITLE
Отсутствие атаки

### ISSUE THREAD

**Issue by Sha-a-ake** [Sha-a-ake/There-s-no-space-for-peace#2]
Атака на пробел
Теперь у каждого врага есть функция IsHit которая срабатывает каждый раз когда герой совершает атаку. Функция проверяет совпали ли координаты цели и атаки и в случае успеха вычитает здоровье цели.

В данный момент герой атакует сразу во всех направлениях. Необходимо добавить направление атаки и добавить анимацию

**Comment by Evg-Mazay** [comment]
Пофиксил Атаку.
